name: app_store_server_sdk
description: Apple App Store Server SDK for facilitating integrations with App Store Server API
homepage: https://github.com/Omnimind-Ltd/app-store-server-sdk
version: 1.2.9

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  json_annotation: ^4.9.0
  http: ^1.2.2
  logging: ^1.2.0
  uuid: ^4.4.2
  jose: ^0.3.4

dev_dependencies:
  lints: any
  test: any
  build_runner: any
  json_serializable: any

false_secrets:
  - /test/app_store_server_sdk_test.dart